services:
  webapi:
    image: webapi
    build:
      context: .
      dockerfile: src/WebApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5678:80"
    depends_on:
      - db
      - caching
      - proxy
  
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=KNKnu2rbsf8sii
      - POSTGRES_DB=acoustics
    ports:
      - "5432:5432"
  
  caching:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"